db.bandas.drop();

db.bandas.insertMany([
	{
		solista: "VER K BITCH",
		genero: "INSTRUMENTAL",
		fecha_inscripcion: new Date(2018, 0, 20),
		discos: [
			{ nombre: "DIOS AGUJERO NEGRO", anio: 2008 },
			{ nombre: "APICHONADOS", anio: 2007 },
			{ nombre: "MERIDIANO", anio: 2006 },
			{ nombre: "CAUSALIDADES", anio: 2005 },
			{ nombre: "PLANETA ESMERALDA", anio: 2001 },
		],
		barrio: "VERSALLES",
		integrantes: 1,
	},
	{
		solista: "TROTAMUNDOS",
		genero: "INDIE",
		fecha_inscripcion: new Date(2017, 10, 30),
		discos: [{ nombre: "HECHO BOLITA", anio: 2014 }],
		barrio: "VILLA LURO",
		integrantes: 4,
	},
	{
		solista: "EFECTO ALFONS",
		genero: "ROCK",
		estilo: "POWER TRIO",
		fecha_inscripcion: new Date(2017, 10, 27),
		discos: [{ nombre: "EFECTO ALFONS", anio: 2000 }],
		barrio: "BARRACAS",
		integrantes: 3,
	},
	{
		solista: "MARCELO GIULITTI",
		genero: "SOLISTA",
		fecha_inscripcion: new Date(2017, 10, 26),
		barrio: "AGRONOMIA",
		integrantes: 1,
	},
	{
		solista: "AFTERLIFE",
		genero: "ROCK",
		estilo: "ROCK ALTERNATIVO",
		fecha_inscripcion: new Date(2017, 10, 14),
		barrio: "BALVANERA",
		integrantes: 5,
	},
	{
		solista: "VIRGINIA FERREYRA",
		genero: "ROCK",
		estilo: "ROCK POP",
		fecha_inscripcion: new Date(2017, 10, 14),
		barrio: "VILLA DEL PARQUE",
		integrantes: 1,
	},
	{
		solista: "LMV",
		genero: "POP",
		fecha_inscripcion: new Date(2017, 10, 10),
		barrio: "LA LUCILA",
		integrantes: 6,
	},
	{
		solista: "EFECTO ALFONS",
		genero: "ROCK",
		estilo: "POWER TRIO",
		fecha_inscripcion: new Date(2017, 10, 6),
		discos: [{ nombre: "EFECTO ALFONS", anio: 1995 }],
		barrio: "BARRACAS",
		integrantes: 3,
	},
	{
		solista: "TANTAS PREGUNTAS",
		genero: "PUNK",
		estilo: "PUNK ROCK",
		fecha_inscripcion: new Date(2017, 9, 27),
		discos: [
			{ nombre: "DESPUES DE TODO", anio: 2006 },
			{ nombre: "LIBRE ALBEDRIO", anio: 2006 },
		],
		barrio: "MORENO",
		integrantes: 3,
	},
	{
		solista: "TAL VEZ DE PASO",
		genero: "POP",
		estilo: "POP ROCK",
		fecha_inscripcion: new Date(2017, 9, 26),
		barrio: "PUERTO MADERO",
		integrantes: 4,
	},
	{
		solista: "LA SURTIDA FOLCK",
		genero: "FOLKLORE",
		fecha_inscripcion: new Date(2017, 9, 25),
		barrio: "BERAZATEGUI",
		integrantes: 7,
	},
	{
		solista: "JAYDEE M",
		genero: "HIP HOP / RAP",
		fecha_inscripcion: new Date(2017, 9, 24),
		barrio: "BARRACAS",
		integrantes: 1,
	},
]);
